---
- hosts: web
  sudo: yes
  tasks:
  - name: Install Apache Packages
    apt: name=apache2 state=present
  - name: Start the Service
    service: name=apache2 state=started

- hosts: web:db
  sudo: yes
  tasks:
  - name: Stop the Firewall
    shell: "ufw disable"
